// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'facebook';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String FACEBOOK_IMG = 'assets/images/Facebook_img.png';
  static const String PHOTOS_IMG = 'assets/images/Photos_img.png';
  static const String PROFILE_IMG = 'assets/images/Profile_img.png';
  static const String STORY_IMG = 'assets/images/Story_img.png';
  static const String BRANDING_IMG = 'assets/images/branding_img.png';
  static const String CHAT_DOTS_IMG = 'assets/images/chat_dots_img.png';
  static const String FACEBOOKBRANDING_IMG = 'assets/images/facebookBranding_img.png';
  static const String FACEBOOKLOGO_IMG = 'assets/images/facebookLogo_img.png';
  static const String HOME_IMG = 'assets/images/home_img.png';
  static const String LOGO_IMG = 'assets/images/logo_img.png';
  static const String MESSI = 'assets/images/messi.png';
  static const String ROUTE_IMG = 'assets/images/route_img.png';
  static const String ROUTE_PROFILE = 'assets/images/route_profile.png';
  static const String MAIN_SVG_LOGO = 'assets/svg/main_svg_logo.svg';
  static const String META_LOGO = 'assets/svg/meta_logo.svg';
}
